# preinstall R dependencies from conda-forge so that they don't all have to get built from source

channels:
  - r  # use offical R channel not conda-forge due to 
dependencies:  
  # deps for r5r
  - r-checkmate
  - r-data.table
  - r-jdx
  - r-rjava
  - r-sf
  - r-sfheaders
  - r-covr
  - r-knitr
  - r-mapview
  - r-rmarkdown
  - r-testthat
  - r-ggplot2
  - r-rcpp==1.0.5

  # deps for paper code
  - r-akima