# preinstall R dependencies from conda-forge so that they don't all have to get built from source

dependencies:  
  # deps for r5r
  - r-base>=4
  - r-irkernel>=1.1
  - r-checkmate
  - r-data.table
  - r-rjava
  - r-sf
  - r-sfheaders
  - r-covr
  - r-knitr
  - r-mapview
  - r-rmarkdown
  - r-testthat
  - r-ggplot2
  - r-rcpp
  - main::openjdk  # use main to get java 11

  # deps for paper code
  - r-akima