#!/bin/bash

set -ex

# use system Java (need Java 11 for R5)
JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/bin/ R CMD javareconf

export LD_LIBRARY_PATH=/srv/conda/envs/notebook/lib:$LD_LIBRARY_PATH

# install JDX (not on conda-forge)
R --no-save <<EOF
install.packages('jdx', repos='https://cloud.r-project.org/')
EOF

# install the R package from local source
R CMD INSTALL r-package